#       Testing script.

command /setteamspawn <text> <text>:

    permission: *
    trigger:

        set {_loc} to player's location
        set {_return} to ArcadeLib_SetTeamSpawn(arg-1, arg-2, {_loc})
        send {_return} to player

command /creategame <text>:

    permission: *
    trigger:


        set {_return} to ArcadeLib_CreateGame(arg-1)
        send {_return} to player

command /addteam <text> [<text>]:

    permission: *
    trigger:


        set {_return} to ArcadeLib_AddTeam(arg-1, arg-2)
        send {_return} to player

command /purgedata:

    permission: *
    trigger:

        set {_return} to ArcadeLib_PurgeData()
        send {_return} to player

on load:

    loop {arcadelib.data.games?::*}:

        send loop-value to console